### ISSUE TITLE
Add the blog links on chain-z in README

### ISSUE THREAD

**Issue by Nishant-sehgal** [intuit/chain-z#19]
One such link:
https://medium.com/@manishmishra039/chain-z-mastering-asynchronous-execution-with-rxjava-a-game-changer-for-java-based-applications-3e25cbe57ef8

**Comment by Nishant-sehgal** [comment]
> i would like to work on this issue,Could you assign me this.

Yes go ahead. Just add small section in the readme that talks about this and refer to the link above.

**Comment by REETI-SARUP** [comment]
Hi @Nishant-sehgal, is this issue still open, can I take it
